/* 
 * File:   main.cpp
 * Author: Tony Reyes
 * June 25, 2014, 3:43 PM
 * Purpose: Gaddis 7thEd #2 Sales Prediction
 */

//System Library
#include <iostream>
using namespace std;

//User Defined Libraries

//Global Constants

//Function Prototypes

//Execution Begins Here!
int main(int argc, char** argv){
   
    //Declare and initialize variables
    float Ecsd= 0.62f; //Percentage of sales for East Sales Div.
    float totSale= 4.6e+6f; //Total Number of Company Sales
    int unsigned totEcsd; //Amount Generated by East Sales Div.
    
    //Calculate Amount Generated by Company
    totEcsd= Ecsd*totSale; 
    
    //Output the Results
    cout<< "Percentage of Sales= " <<Ecsd<<endl;
    cout<<"Total Amount of Sales= " <<totSale<<endl;
    cout<<"Amount Generated by East Div= " <<totEcsd<<endl;
    
    //Exit stage right!   
    return 0;
}
